### PR TITLE
[Desktop] Menu tag assignment

### LINKED ISSUE #646: Menu tag assignment
### Describe the bug

Assigning tags in the explorer context menu throws an error, when `objectData` is null. The one throwing the error is the `tags.getForObject` query in `AssignTagMenuItems` when `objectId === 0`.

image

### Reproduction

1. Open the context menu
2. Highlight the "Assign tag" menu item and wait.

### Expected behavior

_No response_

### Platform and versions

```Shell
7.29.0
cargo 1.67.1 (8ecd4f20a 2023-01-10)
rustc 1.67.1 (d5a82bbd2 2023-02-07)
```

### Stack trace

```Shell
[Error] React Router caught the following error during render (2)
RSPCError: error deserializing procedure arguments
{componentStack: "↵AssignTagMenuItems@http://localhost:8001/@fs/User…lhost:8001/App.tsx?t=1680094927384:77:12↵Suspense"}
	componentDidCatch (chunk-FY2EIZHU.js:3092)
	callback (chunk-WLI4IMR5.js:14088)
	callCallback (chunk-WLI4IMR5.js:10511)
	commitUpdateQueue (chunk-WLI4IMR5.js:10528)
	commitLayoutEffectOnFiber (chunk-WLI4IMR5.js:17065)
	commitLayoutMountEffects_complete (chunk-WLI4IMR5.js:17976)
	commitLayoutEffects_begin (chunk-WLI4IMR5.js:17965)
	commitLayoutEffects_begin (chunk-WLI4IMR5.js:17946)
	commitLayoutEffects (chunk-WLI4IMR5.js:17916)
	commitRootImpl (chunk-WLI4IMR5.js:19349)
	commitRoot (chunk-WLI4IMR5.js:19273)
	finishConcurrentRender (chunk-WLI4IMR5.js:18756)
	performConcurrentWorkOnRoot (chunk-WLI4IMR5.js:18714)
	performConcurrentWorkOnRoot
	workLoop (chunk-WLI4IMR5.js:197)
	flushWork (chunk-WLI4IMR5.js:176)
	performWorkUntilDeadline (chunk-WLI4IMR5.js:384)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by niikeec**
Changes made to the explorer item context menu:
- Show "Assign tag" sub menu only when objectData is present
- Added an option to create tags from the "Assign tag" sub menu(upon creation, the tag is assigned to that object)
- Put "Assign tag" sub menu items into a virtual list.
- Moved AssignTagMenuItems component into its own file, as the same component is used in the item inspector

Changes made to the item inspector:
- Show "Add tag" placeholder only when objectData is present
- Added a tag assignment dropdown menu to the "Add tag" placeholder(uses the AssignTagMenuItems component)

image

Closes #646

### CODE REVIEW

File: interface/app/$libraryId/settings/library/tags/CreateDialog.tsx [hunk 1]
```diff
@@ -20,14 +20,23 @@ export default (props: UseDialogProps) => {
 	});
 
 	const createTag = useLibraryMutation('tags.create', {
-		onSuccess: () => {
+		onSuccess: (tag) => {
 			submitPlausibleEvent({ event: { type: 'tagCreate' } });
+			if (props.assignToObject) {
```
Comment (Brendonovich) [inline interface/app/$libraryId/settings/library/tags/CreateDialog.tsx:25]: This won't work if `assignToObject` is 0 - do an `undefined` check instead

**Review by Brendonovich — CHANGES_REQUESTED** [review]

**Review by Brendonovich — APPROVED** [review]
