### PR TITLE
SearchBar Logo fix

### LINKED ISSUE #295: [ENG-113] Search bar on location page shows macOS Command logo for keybind on non-macOS systems

### PR DESCRIPTION
**Pull request by misxki**
The SearchBar shows now CTRL for the keybind on non-macOS systems.

Closes #295

### CODE REVIEW

**Comment by RockBacon9922** [comment]
Was this ever merged @misxki?

**Comment by xPolar** [comment]
@RockBacon9922 misxki can't merge this PR, only the core team can, any ETA on review / merge @jamiepine @maxichrome

**Review by maxichrome — APPROVED** [review]
sick change! sorry for holding off so long — was waiting on license change!

File: packages/interface/src/components/layout/TopBar.tsx [hunk 1]
```diff
@@ -49,6 +51,23 @@ const TopBarButton: React.FC<TopBarButtonProps> = ({ icon: Icon, ...props }) =>
...
+	const appProps = useContext(AppPropsContext);
+
+	return (					
+		<div className="relative flex h-7">
+			<input
+				placeholder="Search"
+				className="w-32 h-[30px] focus:w-52 text-sm p-3 rounded-lg outline-none focus:ring-2  placeholder-gray-400 dark:placeholder-gray-500 bg-[#F6F2F6] border border-gray-50 dark:bg-gray-650 dark:border-gray-550 focus:ring-gray-100 dark:focus:ring-gray-600 transition-all"
+			/>
+			<div className="space-x-1 absolute top-[2px] right-1">
+				<Shortcut chars={ appProps?.platform === "macOS" ? "⌘K" : "CTRL+K" } />
```
Comment (maxichrome) [inline packages/interface/src/components/layout/TopBar.tsx:64]: I'd like to see detection for platform on web implemented as well -- this is probably more of an app-level architectural thing. until then, before merge, could we get the cmd-k visual to show on web as well?

**Review by maxichrome — CHANGES_REQUESTED** [review]
reverted approval for one requested change -- then I'm happy to merge :D

**Review by maxichrome — APPROVED** [review]
tysm for following up with requested changes @misxki :)

once CI runs finish here I'd be happy to merge.
