### PR TITLE
[Desktop] Fix menu colors and arrow highlighting

### LINKED ISSUE #638: Menu colors and arrow highlighting
### Describe the bug

1. Light theme uses dark colors and the line color on the dark theme is barely visible.

image

2. Highlighting menu items with arrow keys doesn't properly highlight them.

image

### Reproduction

_No response_

### Expected behavior

_No response_

### Platform and versions

```Shell
7.29.0
cargo 1.67.1 (8ecd4f20a 2023-01-10)
rustc 1.67.1 (d5a82bbd2 2023-02-07)
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by niikeec**
Changes made:
- Changed light theme menu colors
- Changed dark theme menu line color to a slightly lighter one
- Slightly increased menu size for a better look
- Added menu item arrow highlighting
- Removed absolute key bind position, that way long labels don't clash with the key bind
- Removed animate prop from the dropdown menu and make it animate by default

Will PR tag related changes after this is resolved.

image

Closes #638

### CODE REVIEW

File: packages/ui/src/ContextMenu.tsx [hunk 1]
```diff
@@ -48,33 +44,38 @@ const SubMenu = ({
...
-		'flex flex-1 flex-row items-center justify-start overflow-hidden',
-		'space-x-2 px-2 py-[3px]',
-		'cursor-default rounded',
-		'focus:outline-none'
+		'flex h-[26px] items-center space-x-2 overflow-hidden rounded px-2',
+		'text-ink text-sm',
+		'group-radix-highlighted:text-white dark:group-radix-highlighted:text-ink',
+		'group-radix-highlighted:text-white dark:group-radix-highlighted:text-ink',
+		'group-radix-disabled:text-ink/50 group-radix-disabled:pointer-events-none',
+		'group-radix-state-open:bg-accent group-radix-state-open:text-white dark:group-radix-state-open:text-ink'
```
Comment (Brendonovich) [inline packages/ui/src/ContextMenu.tsx:69]: I'm not sure some of the colours here should be hardcoded to `text-white`, since that breaks custom theme support. Instead only colours like `text-ink` should be used since the adapt to whatever theme is being used - even custom themes.

**Review by Brendonovich — CHANGES_REQUESTED** [review]
the state of our dropdowns is horrendous and i apologise

File: packages/ui/src/ContextMenu.tsx (hunk 1 above)
Comment (utkubakir) [reply packages/ui/src/ContextMenu.tsx:69]: `text-white` is used almost everywhere on the desktop though. It's fine for now IMO. We are gonna have to change a lot of places when we roll out the full custom theme support anyway.

Comment (Brendonovich) [reply packages/ui/src/ContextMenu.tsx:69]: Idk, we've already got a bunch of theme colors and `text-ink` is already being used. May as well keep at it.
image

Comment (niikeec) [reply packages/ui/src/ContextMenu.tsx]: White was used for a reason, otherwise, you get this, as color-ink on light theme is of a darker color

image

Comment (Brendonovich) [reply packages/ui/src/ContextMenu.tsx]: ok that can be a jamie problem haha

**Review by Brendonovich — APPROVED** [review]
