### PR TITLE
Fix thumbnails and file previews on Linux

### LINKED ISSUE #634: Thumbnail and File preview not working on Linux
### Describe the bug

Hello,

Currently, file thumbnails and previews are not functioning correctly on Linux systems (as tested on Arch Linux and Fedora 37):
image
image

Based on my investigations, these issues seem to stem from the custom HTTP server that is employed only on Linux, due to an incompatibility with tauri custom protocol handling:
https://github.com/spacedriveapp/spacedrive/blob/c2666f7f63b48a1210cc1d8798a512c311b522ae/apps/desktop/src-tauri/src/main.rs#L49-L56

When I attempted to make a direct request to the link that serves a thumbnail using a browser, the server logs displayed a panic due to calling `Result::unwrap() on an Err`. Simultaneously, the browser displayed `a connection was reset` error:
image
image

Based on the stack trace, the unwrap call is made in the following line:
https://github.com/spacedriveapp/spacedrive/blob/c2666f7f63b48a1210cc1d8798a512c311b522ae/apps/desktop/src-tauri/src/app_linux.rs#L68

After researching the axum docs, it appears that the error is due to the `auth_middleware` being set inside a nested route. These routes only receive partial URIs, which leads to failure when trying to call `Url::parse`, as it requires an absolute URL string to be passed.
https://github.com/spacedriveapp/spacedrive/blob/c2666f7f63b48a1210cc1d8798a512c311b522ae/apps/desktop/src-tauri/src/app_linux.rs#L34-L40
https://docs.rs/axum/0.6.4/axum/extract/struct.OriginalUri.html
https://docs.rs/url/latest/url/struct.Url.html#method.parse

A possible solution to this issue is to use the `OriginalUri` extractor for axum. However, I think it would be better to restructure the code to rely solely on axum's primitives. I will submit a pull request later today that implements a possible solution.

### Reproduction

1. Run the desktop app on a Linux environment.
2. Add a location containing images to the app.
3. Open the location within the app.
4. Thumbnails of image files do not render correctly, appearing as broken images.
5. Attempts to preview files result in a `Message Corrupt ` error message.

### Expected behavior

Thumbnails of image files are rendered correctly and file previews are loaded

### Platform and versions

```Shell
$> pnpm --version && cargo --version && rustc --version
7.30.5
cargo 1.68.1
rustc 1.68.1 (8460ca823 2023-03-20) (Arch Linux rust 1:1.68.1-1)
$> uname -a
Linux arch.shadowverse 6.2.6-201.fsync.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 15 04:41:53 UTC 2023 x86_64 GNU/Linux
```

### Stack trace

```Shell
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase', apps/desktop/src-tauri/src/app_linux.rs:68:54
stack backtrace:
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBasecalled `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase', ', apps/desktop/src-tauri/src/app_linux.rsapps/desktop/src-tauri/src/app_linux.rs::thread '6868tokio-runtime-worker::' panicked at '5454called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase

', apps/desktop/src-tauri/src/app_linux.rs:68:54
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase', apps/desktop/src-tauri/src/app_linux.rs:68:54
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase', apps/desktop/src-tauri/src/app_linux.rs:68:54
   0:     0x556ed8f46faa - std::backtrace_rs::backtrace::libunwind::trace::h0759ab61a7df5ca3
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x556ed8f46faa - std::backtrace_rs::backtrace::trace_unsynchronized::h373d5243fdf881fe
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x556ed8f46faa - std::sys_common::backtrace::_print_fmt::h6ef19941e003c069
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x556ed8f46faa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0082bce5b70fbc59
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x556ed8f71a4e - core::fmt::write::hff7781a80ac6e1db
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/fmt/mod.rs:1213:17
   5:     0x556ed8f40205 - std::io::Write::write_fmt::hcf35a78ac81c4c01
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/io/mod.rs:1682:15
   6:     0x556ed8f46d75 - std::sys_common::backtrace::_print::hfbf9ea42100c2af6
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x556ed8f46d75 - std::sys_common::backtrace::print::hc4f3f89884134f88
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x556ed8f4881f - std::panicking::default_hook::{{closure}}::h23da7d6ab4434891
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:267:22
   9:     0x556ed8f4855b - std::panicking::default_hook::h004a912370fb71d6
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:286:9
  10:     0x556ed8f48f29 - std::panicking::rust_panic_with_hook::h05e3c7ae2fc70672
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:688:13
  11:     0x556ed8f48cc9 - std::panicking::begin_panic_handler::{{closure}}::hd6b6474644efc47e
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:579:13
  12:     0x556ed8f4745c - std::sys_common::backtrace::__rust_end_short_backtrace::heb68d0d9bb092d91
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x556ed8f489d2 - rust_begin_unwind
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:575:5
  14:     0x556ed4a75813 - core::panicking::panic_fmt::hff834116a2912728
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:64:14
  15:     0x556ed4a75cc3 - core::result::unwrap_failed::h9b645a1d2f718edd
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/result.rs:1790:5
  16:     0x556ed86e757a - core::result::Result<T,E>::unwrap::h4427621c9f84fad1
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/result.rs:1112:23
  17:     0x556ed5398686 - spacedrive::app_linux::auth_middleware::{{closure}}::h07c95aae56c9c0d2
                               at /home/vitor/Workspace/spacedrive/apps/desktop/src-tauri/src/app_linux.rs:68:12
  18:     0x556ed512a3af - <axum::middleware::from_fn::FromFn<F,S,I,(T1,T2)> as tower_service::Service<http::request::Request<B>>>::call::{{closure}}::h60fd3b34733af887
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.4/src/middleware/from_fn.rs:299:44
  19:     0x556ed8975a88 - <axum::middleware::from_fn::ResponseFuture as core::future::future::Future>::poll::hc5ab984e04b8dbdd
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.4/src/middleware/from_fn.rs:380:9
  20:     0x556ed512aecb - <F as futures_core::future::TryFuture>::try_poll::h581a7bd709e69745
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/future.rs:82:9
  21:     0x556ed4e73b11 - <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll::h8569943f4e32ab1c
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/future/try_future/into_future.rs:34:9
  22:     0x556ed50e183d - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h4e7d424490bd023e
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/future/future/map.rs:55:37
  23:     0x556ed5395391 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h093c8573643849ee
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/lib.rs:91:13
  24:     0x556ed4cb5d61 - <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll::hbe004963bb76960f
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/lib.rs:91:13
  25:     0x556ed5503131 - <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll::h80a4ca83533f7ff2
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
  26:     0x556ed5504e1a - <F as futures_core::future::TryFuture>::try_poll::he8375b93a902d375
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/future.rs:82:9
  27:     0x556ed4e73c51 - <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll::he7be21423aca09f9
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/future/try_future/into_future.rs:34:9
  28:     0x556ed50e1f5d - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h8905460f11e5fe50
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/future/future/map.rs:55:37
  29:     0x556ed5395661 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h6f620ae036e85d7c
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/lib.rs:91:13
  30:     0x556ed4cb5ea1 - <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll::h43cb7eb357391a37
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/lib.rs:91:13
  31:     0x556ed51c8a21 - <tower::util::map_err::MapErrFuture<F,N> as core::future::future::Future>::poll::h4758cf2b76e328f6
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
  32:     0x556ed51c7a1a - <F as futures_core::future::TryFuture>::try_poll::h317ab4bce19e74b4
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/future.rs:82:9
  33:     0x556ed4e73bb1 - <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll::hd11e0170c717b6a2
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/future/try_future/into_future.rs:34:9
  34:     0x556ed50e22ed - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h8f542b4adb1443bb
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/future/future/map.rs:55:37
  35:     0x556ed5395611 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h67129e4d60f32b46
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/lib.rs:91:13
  36:     0x556ed4cb5db1 - <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll::hd187faef8c0cf65d
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/lib.rs:91:13
  37:     0x556ed5503221 - <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll::hff7489bc2e0e66fd
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
  38:     0x556ed8985018 - <core::pin::Pin<P> as core::future::future::Future>::poll::h8409f2e66e0e8e91
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/future/future.rs:125:9
  39:     0x556ed50e9cd0 - <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll::h736e7f1a3bf67a56
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/util/oneshot.rs:97:38
  40:     0x556ed4dcf81f - <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll::h907d6f0a4cf7e405
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.4/src/routing/route.rs:164:61
  41:     0x556ed4ddbbb6 - <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg::hb0c819f632534dea
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/proto/h1/dispatch.rs:491:35
  42:     0x556ed4dde714 - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write::h023176314b25843a
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/proto/h1/dispatch.rs:297:43
  43:     0x556ed4de434f - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop::h1f5362ec826d28d1
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/proto/h1/dispatch.rs:161:21
  44:     0x556ed4dde152 - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner::h9ccde5c3489ee075
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/proto/h1/dispatch.rs:137:16
  45:     0x556ed4ddd328 - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch::h881058ae371bb438
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/proto/h1/dispatch.rs:120:28
  46:     0x556ed4ddaecc - <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll::hda0e986d274ce128
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/proto/h1/dispatch.rs:424:9
  47:     0x556ed50e711a - <hyper::server::conn::ProtoServer<T,B,S,E> as core::future::future::Future>::poll::hdf273276b79f33e8
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/server/conn.rs:952:47
  48:     0x556ed50de0e1 - <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll::h4b34670ee8cc4a05
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/server/conn.rs:1012:30
  49:     0x556ed4c64c69 - <hyper::common::drain::Watching<F,FN> as core::future::future::Future>::poll::h77bb24607b884178
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/common/drain.rs:95:36
  50:     0x556ed4db4fba - <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll::h4564c00f6fce3b3b
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/server/server.rs:741:36
  51:     0x556ed543ed6a - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::hc620a6900c2e09d6
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/core.rs:223:17
  52:     0x556ed4e5318f - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hf1489d4f6e79adda
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/loom/std/unsafe_cell.rs:14:9
  53:     0x556ed5433b0a - tokio::runtime::task::core::Core<T,S>::poll::h01d0601e3521096c
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/core.rs:212:13
  54:     0x556ed5211f54 - tokio::runtime::task::harness::poll_future::{{closure}}::h7d2e8a8261fac4b8
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/harness.rs:476:19
  55:     0x556ed54506a3 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4d1fe5addf4f64d2
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panic/unwind_safe.rs:271:9
  56:     0x556ed4b7f10c - std::panicking::try::do_call::h7e98f2fe3889a3c4
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:483:40
  57:     0x556ed4b9a9cb - __rust_try
  58:     0x556ed4b65b71 - std::panicking::try::h7b246dc548c4e78f
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:447:19
  59:     0x556ed4e961ca - std::panic::catch_unwind::h64784db7301bf586
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panic.rs:140:14
  60:     0x556ed51f8913 - tokio::runtime::task::harness::poll_future::h05c79b7dd1024318
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/harness.rs:464:18
  61:     0x556ed52219bb - tokio::runtime::task::harness::Harness<T,S>::poll_inner::hf55693d1a1de7534
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/harness.rs:198:27
  62:     0x556ed5236af3 - tokio::runtime::task::harness::Harness<T,S>::poll::hdbe87e671e7dd489
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/harness.rs:152:15
  63:     0x556ed4a7b0db - tokio::runtime::task::raw::poll::h4c1a97a811a150c4
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/raw.rs:255:5
  64:     0x556ed8e6f568 - tokio::runtime::task::raw::RawTask::poll::hca805701aae5f719
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/raw.rs:200:18
  65:     0x556ed8e78d52 - tokio::runtime::task::LocalNotified<S>::run::h6dd52284cc3c2177
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/mod.rs:394:9
  66:     0x556ed8deb37c - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}::he617d89beb5dd15e
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:464:13
  67:     0x556ed8deb20e - tokio::runtime::coop::with_budget::heba41c23af0290c4
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/coop.rs:107:5
  68:     0x556ed8deb20e - tokio::runtime::coop::budget::h32c503dcf1f79e3e
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/coop.rs:73:5
  69:     0x556ed8deb20e - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hdce0b2b1af98e7e1
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  70:     0x556ed8dea931 - tokio::runtime::scheduler::multi_thread::worker::Context::run::h3a688a8d7f45624c
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  71:     0x556ed8dea6ed - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::hbfa3cc7830ff4512
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  72:     0x556ed8de7837 - tokio::macros::scoped_tls::ScopedKey<T>::set::h874738b5a30092c6
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/macros/scoped_tls.rs:61:9
  73:     0x556ed8dea54f - tokio::runtime::scheduler::multi_thread::worker::run::h7906d5695c870972
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  74:     0x556ed8dea2eb - tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}::h839a93ac0c880867
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  75:     0x556ed8e70f3e - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::he574cbcf850da2b0
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/blocking/task.rs:42:21
  76:     0x556ed8e8d2b0 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h098e29a522750227
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/core.rs:223:17
  77:     0x556ed8e308df - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h9adae7ffb05918f4
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/loom/std/unsafe_cell.rs:14:9
  78:     0x556ed8e8d0fe - tokio::runtime::task::core::Core<T,S>::poll::hee8fdf6edc44d858
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/core.rs:212:13
  79:     0x556ed8e15f88 - tokio::runtime::task::harness::poll_future::{{closure}}::hdaaea5133216f740
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/harness.rs:476:19
  80:     0x556ed8e47df3 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf82b41d58b032074
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panic/unwind_safe.rs:271:9
  81:     0x556ed8e934fd - std::panicking::try::do_call::h2bfdeeec08ffbc36
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:483:40
  82:     0x556ed8e968eb - __rust_try
  83:     0x556ed8e924c1 - std::panicking::try::hc6acfbec4a495046
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:447:19
  84:     0x556ed8e01ffb - std::panic::catch_unwind::h0901130ca459c806
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panic.rs:140:14
  85:     0x556ed8e13d84 - tokio::runtime::task::harness::poll_future::h1984e3f8e3e3d553
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/harness.rs:464:18
  86:     0x556ed8e0ef29 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h8c9d3fe469610bfb
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/harness.rs:198:27
  87:     0x556ed8e0e577 - tokio::runtime::task::harness::Harness<T,S>::poll::h06ca8a29585c31aa
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/harness.rs:152:15
  88:     0x556ed8e6f7ed - tokio::runtime::task::raw::poll::hafb49d65631fcdf0
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/raw.rs:255:5
  89:     0x556ed8e6f568 - tokio::runtime::task::raw::RawTask::poll::hca805701aae5f719
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/raw.rs:200:18
  90:     0x556ed8e78e17 - tokio::runtime::task::UnownedTask<S>::run::h65cdd588f1d45e34
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/mod.rs:431:9
  91:     0x556ed8deebf7 - tokio::runtime::blocking::pool::Task::run::h0bf36e3565d4fd31
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/blocking/pool.rs:159:9
  92:     0x556ed8df410c - tokio::runtime::blocking::pool::Inner::run::h489c8f7340404036
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/blocking/pool.rs:511:17
  93:     0x556ed8df3644 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h467de47e7987ce48
                               at /home/vitor/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/blocking/pool.rs:469:13
  94:     0x556ed8e2a471 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha5508f328c9c903e
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/sys_common/backtrace.rs:121:18
  95:     0x556ed8e04652 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::heb0348ca7531c81e
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/thread/mod.rs:558:17
  96:     0x556ed8e47cc2 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd5938cd4eb77a42e
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panic/unwind_safe.rs:271:9
  97:     0x556ed8e94eee - std::panicking::try::do_call::hff55cc654e6d8f4e
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:483:40
  98:     0x556ed8e968eb - __rust_try
  99:     0x556ed8e91a43 - std::panicking::try::h7dfac281968e9f2d
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:447:19
 100:     0x556ed8e02710 - std::panic::catch_unwind::heee54e3b5ffd5336
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panic.rs:140:14
 101:     0x556ed8e0443f - std::thread::Builder::spawn_unchecked_::{{closure}}::he2dacc102053af95
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/thread/mod.rs:557:30
 102:     0x556ed8e4841f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h02d7fc356dca418c
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/ops/function.rs:250:5
 103:     0x556ed8f4ee23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h00e86886c43a2f75
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/alloc/src/boxed.rs:1988:9
 104:     0x556ed8f4ee23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa5c45bfaf12e95d
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/alloc/src/boxed.rs:1988:9
 105:     0x556ed8f4ee23 - std::sys::unix::thread::Thread::new::thread_start::h1817c1275a6116a9
                               at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/sys/unix/thread.rs:108:17
 106:     0x7f39f9177bb5 - <unknown>
 107:     0x7f39f91f9d90 - <unknown>
 108:                0x0 - <unknown>
```

### Additional context

Web version works correctly on Linux, thumbnails are rendered correctly and file preview are loaded.

### PR DESCRIPTION
**Pull request by HeavenVolkoff**
Hello,

This PR addresses the thumbnail and file preview issues on Linux that I reported in #634. As I explained in my comment on the issue, the problem stemmed from the `auth_middleware` receiving a partial URI and `Url::parse` failing as a result. To fix this, I replaced `Url::parse` with primitives from Axum, specifically the `Query` and `TypedHeader` extractors:
https://docs.rs/axum/0.6.4/axum/extract/struct.Query.html
https://docs.rs/axum/0.6.4/axum/extract/index.html#running-extractors-from-middleware

By using `TypedHeader` to extract the `Authorization` header, I had to slightly modify the original logic to follow the syntax described in the spec for the value of this header type, which expect  `<auth-scheme> <authorization-parameters>`  instead of just a token value. However, I tested this change and found that it doesn't affect any currently implemented logic, as all requests for this route pass the token as a query parameter.

While testing these changes, I also found some other minor issues that I ended up fixing:
 - Fixed `App.tsx`  reading the incorrect property for the injected token
 - Added the required dependencies for rendering video previews on Linux to the setup script, along with some other minor improvements.

I'm not very experienced with Rust, so please forgive me if I made any mistakes.

Closes #634

### CODE REVIEW

File: apps/desktop/src-tauri/src/app_linux.rs [hunk 1]
```diff
@@ -60,27 +62,38 @@ pub(super) async fn setup<R: Runtime>(
...
+
+		if auth.token() != auth_token {
+			return Err(StatusCode::UNAUTHORIZED);
 		}
+
+		req = Request::from_parts(parts, body);
 	}
 
-	(StatusCode::UNAUTHORIZED, "Unauthorized!").into_response()
+	return Ok(next.run(req).await);
```
Comment (fogodev) [inline apps/desktop/src-tauri/src/app_linux.rs:96]: Every block in Rust returns its last expression, so there is no need for this mutable `req` and also no need for the last return statement. The `req` part you can handle with an else block returning the entire `request` from the block.

**Review by fogodev — CHANGES_REQUESTED** [review]
Aside from my comment, LGTM. Nice catch on gstreamer deps in the Linux part of setup script.

**Review by fogodev — APPROVED** [review]
