### PR TITLE
[ENG-870] Fix wording for delete dialog

### LINKED ISSUE #1384: [ENG-870] Deleting a folder should not say "Deleted 1 file"
It should calculate how many items are in it or even "deleted {folderName}" might work

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-870](https://linear.app/spacedriveapp/issue/ENG-870/deleting-a-folder-should-not-say-deleted-1-file)</sub>

### PR DESCRIPTION
**Pull request by Tilo-K**
*Prefix: I'm really new to the project but wanted to try to tackle an issue, I'm not familiar with the Codebase, so if this is totally wrong or there is need to change something please let me know. I would really appreciate it if someone would take the time to give some feedback on this.*

Currently, the delete dialog always says that you are deleting a file, even if it is a directory or a mix of items.

To fix this:
The DeleteDialog now accepts two props, which specify the type of files to be deleted.
Based on this information, the wording is adjusted.

Example of directory deletion
Example of mix deletion

Closes #1384

### CODE REVIEW

**Review by brxken128 — DISMISSED** [review]
I think the second image should say "Delete x items" if at least one directory and one file is selected, and "Delete x directories" and "Delete x files" if they're just purely files and directories respectively.

For single items, it should say "Delete a file" or "Delete a directory" respectively too.

Would take a little bit more logic, but would definitely provide even better wording and clarity to the user.

File: interface/app/$libraryId/Explorer/FilePath/DeleteDialog.tsx [hunk 1]
```diff
@@ -5,13 +5,26 @@ interface Props extends UseDialogProps {
 	locationId: number;
 	rescan?: () => void;
 	pathIds: number[];
+	includesDirectorys?: boolean;
```
Comment (brxken128) [inline interface/app/$libraryId/Explorer/FilePath/DeleteDialog.tsx:8]: This should be `Directories` :)

File: interface/app/$libraryId/Explorer/FilePath/DeleteDialog.tsx [hunk 2]
```diff
@@ -5,13 +5,48 @@ interface Props extends UseDialogProps {
...
+		prefix = (fileCount + dirCount).toString();
+	}
+
+	return { type, prefix };
 }
 
 export default (props: Props) => {
 	const deleteFile = useLibraryMutation('files.deleteFiles');
+	props.dirCount ??= 0;
+	props.fileCount ??= 0;
```
Comment (ameer2468) [inline interface/app/$libraryId/Explorer/FilePath/DeleteDialog.tsx:42]: This is great, tested the PR and works as expected. However these 2 lines of code needs to be adjusted.

Directly mutating props like this in a React component is considered a bad practice. Props in React components are meant to be read-only and should not be modified. If you're looking to set default values for props, consider using defaultProps or set them before passing them into the component.

Comment (Tilo-K) [reply interface/app/$libraryId/Explorer/FilePath/DeleteDialog.tsx]: Thank you for the feedback, I implemented the first suggestion.

**Review by ameer2468 — APPROVED** [review]

**Comment by ameer2468** [comment]
Thanks for the response @Tilo-K 

I have done testing. Currently this implementation only considers the count when you press Delete within the context menu, however, when using the shortcut on keyboard to delete, it does not count.

**Comment by Tilo-K** [comment]
Sorry for the delay @ameer2468
I now also added the file / directory counts to the shortcut. This should work now.

**Review by ameer2468 — APPROVED** [review]
Good work! tested and works well.
