### PR TITLE
Fix `xdg-open` for Trash

### LINKED ISSUE #2546: Trash isn't opening on Linux
### Describe the bug

Trash directory doesn't open

### Reproduction

1. Open Spacedrive
2. Click Trash
3. Nothing appears

### Expected behavior

Trash folder should open in the default xdg application

### Platform and versions

```Shell
pnpm 9.2.0
cargo 1.78.0 (54d8815d0 2024-03-26)
rustc 1.78.0 (9b00956e5 2024-04-29)
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gedeondoescode**
Closes #2546

### CODE REVIEW

File: apps/desktop/src-tauri/src/main.rs [hunk 1]
```diff
@@ -155,8 +155,10 @@ async fn open_trash_in_os_explorer() -> Result<(), ()> {
 
 	#[cfg(target_os = "linux")]
 	{
+		let linux_path = format!("{}/.local/share/Trash", std::env::var("HOME").unwrap());
```
Comment (HeavenVolkoff) [inline apps/desktop/src-tauri/src/main.rs:158]: Not a fan of this unwrap. This error should be handled just he the spawn error bellow.

**Review by HeavenVolkoff — CHANGES_REQUESTED** [review]

**Review by HeavenVolkoff — APPROVED** [review]
