### PR TITLE
Fix closing tag window

### LINKED ISSUE #1769: "String must contain..." when closing tag window
### Describe the bug

When I open the "New Tag" Window and click on "Close" without any cahnges made, I get the warning "String must contain at least 1 character(s)". Clicking on "Close" a second time actually closes the window.

### Reproduction

_No response_

### Expected behavior

I would expect to for the window to be closed without a warning.

### Platform and versions

```Shell
Spacedrive for macOS v0.1.2 - 83538f2
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by utkubakir**
Fixes #1769

### CODE REVIEW

File: interface/app/$libraryId/settings/library/tags/CreateDialog.tsx [hunk 1]
```diff
@@ -54,7 +54,7 @@ export default (
 	const form = useZodForm({
 		schema: schema,
 		defaultValues: { color: '#A717D9' },
-		mode: 'onBlur'
+		mode: 'onSubmit'
```
Comment (niikeec) [inline interface/app/$libraryId/settings/library/tags/CreateDialog.tsx:57]: We don't really have to use mode here as it's "onSubmit" by default

**Review by niikeec — CHANGES_REQUESTED** [review]

**Review by niikeec — APPROVED** [review]
